dist: xenial
language: minimal
git:
  depth: 1
  submodules: false
env:
  global:
    - CC="gcc-7"
    - EXTRA_CFLAGS="-O2"
    - LDFLAGS="-static"
script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-7 libjansson-dev -y
  - git submodule update --init --recursive --depth 1 || exit 1
  - make -j $(nproc) -C ./plotnetcfg || exit 1
  - cd ./plotnetcfg
  - sha256sum plotnetcfg > plotnetcfg.sha256
  - file plotnetcfg
  - cat plotnetcfg.sha256
deploy:
  provider: releases
  api_key:
    secure: "Rw5l0weiVI1zVamPEXDYJxfGoy52kNGSfTDGNaEkMraL28q0F/RYZLuFjd4KRK9Wz8wYFdqQGMK/t84mAmNxxQjl//rP8vTHwWdJiyRSGXeOedMSMEoT2TrKTRUj30+Z9iXidnYvAmAcrshhj+HZByO4Ty3InrLilocYNm0XYF4YNrruI9CqwOupJdC56GUpr6Zo3WDRHi5ZbLg2WUqHQQN9yVzvt+E+D6Oe8PP6KTRbz/CxwBB7v6Pax+KM0K6DRDfYrrXYqSnunjUZ5VuIe2Yd0tuRnQ66l6WKnG/PCHGvGByW8Sb1kbJfsbvASxnpGzj3kkIYxO7bNyvUNa9T/dCigrkQ3svmwoFMOq1RWXiRPMF/BYWcEnJqwzO79ZJ0Csfq+CdYKhxzhzlXLNIkLndfYWbPFuvidROkNZUiUx595H6lVcwKG/LfXn/50CWdN+hTavncC7/HLCY+oHtBKD+5u1iL3uRbmdQwcfTdLCWV0gQzsneXeB7HVjpUz0KCrQeygt8bX1/LMjgh3Gu7oD2f/EU+jYcmDox1NTc/cxK/PgVyL3GZz2IXbYf8P60ZoIBYEywn+/MYOrW+sqoGOTtGUIw+heBFcJLeNXIp6q5CGbrEFTRw8x7C7TfTbQbE1EmRYTk7xQ1sRJ8GnTeC4w4YCDB+FkUQMdxfN2bW1UY="
  file_glob: true
  file:
    - "plotnetcfg"
    - "plotnetcfg.sha256"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
